### ISSUE TITLE
Is there some way to test this?

### ISSUE THREAD

**Issue by GBeushausen** [canyongbs/advisingapp#915]
Hi,

is there some way to test this app or see screenshots? The link is not working, both to this advisingapp url and the url of the manufacturer. Cloudflare says i'm blocked. This also happens with using VPN's, so i guess the site is down.

Then i tried to install it locally but the documentation uses a "spin" command. What is spin, from where do i get this? docker compose doesn't work the created advisingapp comtainer is immediatly terminating after creation.

Thanks.

**Comment by Orrison** [comment]
Hey @GBeushausen, sorry for the delay in getting back to you.

To clarify, the sites for our product are currently up. However, they are only available to certain international markets at this time. These include the United States, Canada, the United Kingdom, India, and the Philippines. Other factors can also contribute to a block, such as VPNs or some other type of threat detection trigger.

The spin command mentioned in the docs can be found and installed on their official website: https://serversideup.net/open-source/spin/docs

We are working on improving the local setup steps over time. Sometimes, you may need to stop and start the container after you have run the commands listed in the local setup docs.
